In [1]:
import numpy as np

matrix_a=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_b = np.eye(3)

result=np.dot(matrix_a,matrix_b)

print("matrix A:\n",matrix_a)
print("Identity matrix B:\n",matrix_b)
print("Multiplication result:\n",result)

matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Identity matrix B:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Multiplication result:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [2]:
import numpy as np
 
word_embeddings=np.array([[1.0,1.2],[0.9,1.1],[-1.0,-0.8]])

apple_query=word_embeddings[0]
scores=np.dot(word_embeddings,apple_query)

print("Apple与各个词的相似度分数:", scores)

Apple与各个词的相似度分数: [ 2.44  2.22 -1.96]
