In [1]:
import numpy as np

matrix_a=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_b = np.eye(3)

result=np.dot(matrix_a,matrix_b)

print("matrix A:\n",matrix_a)
print("Identity matrix B:\n",matrix_b)
print("Multiplication result:\n",result)

matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Identity matrix B:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Multiplication result:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
